[package]
name = "axum-dev-only"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tower-livereload = { path = "../.." }
