[package]
name = "axum-htmx"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.7"
notify = "8.2.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.7", features = ["fs"] }
tower-livereload = { path = "../.." }
