[package]
name = "axum-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tower-livereload = { path = "../.." }
